version: "3.3"
services:
  web:
    image: jtl-tkgiharbor.hq.bni.co.id/bni-nextsoa-dev/mail_service
    build: .
    ports:
      - "9111:9090"
    networks:
      - web_net
    volumes:
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "192M"
      replicas: 2
    environment:
      ENV_DB_USER: "soa_app"
      ENV_DB_PASS: "soaapp123" #old soa_app, new soaapp123
      ENV_DB_HOST: "soa.ora"
      ENV_DB_PORT: "1686" #old 1572, new 1686
      ENV_DB_SID: "soasysqa" #old soasysdev, new soasysqa
      ENV_MAIL_HOST: "smtp.gmail.com"
      ENV_MAIL_PORT: 465
      ENV_MAIL_USER: "adityarachman24.ar@gmail.com"
      ENV_MAIL_PASS: "gilfdgrwojoxciab"
      ENV_MAIL_TLS: True
      # ENV_LIVENESS_ENDPOINT: "http://soa.ext:8180/verijelas/liveness_detection"
      # ENV_LIVENESS_V2_ENDPOINT: "http://soa.ext:8180/verijelas/liveness_detection/v2"
    extra_hosts:
      - "soa.dp:192.168.143.61"
      - "soa.ps:192.168.143.27"
      - "soa.ext:192.168.152.220"
      - "soa.int:192.168.151.220"
      - "soa.ora:192.168.143.93"
      - "soa.ora.old:192.168.132.81"
      - "gitlab.bni.co.id:192.168.150.100"
networks:
  web_net:
    driver: overlay
    attachable: true
    #ipam:
    #  config:
    #    - subnet: 172.18.0.0/27